module.exports = {
    // Specify the database dialect (type of database)
    // In this case, we're using SQLite
    dialect: "sqlite",

    // Specify the storage location for the SQLite database file
    // This is equivalent to specifying the database file path in a SQLite connection string
    storage: "./library.sqlite",

    // Disable logging; default: console.log
    logging: false
    // Try enabling logging to see the SQL queries generated by Sequelize
    // logging: (msg) => {
    //     console.log("[Sequelize]", msg)
    // }
}
